version: "3.9"
x-environment:
  &QUICKSTART_ENVIRONMENT # These are read from .env file. The values in the .env file maybe overriden by shell envvars
#  PLAID_CLIENT_ID: ${PLAID_CLIENT_ID:?err}
#  PLAID_SECRET: ${PLAID_SECRET:?err}
#  PLAID_PRODUCTS: ${PLAID_PRODUCTS:?err}
#  PLAID_COUNTRY_CODES: ${PLAID_COUNTRY_CODES:?err}
#  PLAID_REDIRECT_URI: ${PLAID_REDIRECT_URI:?err}
#  PLAID_ENV: ${PLAID_ENV:?err}
#  SPLITWISE_API_KEY: ${SPLITWISE_API_KEY:?err}
services:
  go:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./go/Dockerfile
    ports: ["8000:8000"]
#    environment:
#      <<: *QUICKSTART_ENVIRONMENT
#    Uncomment env_file when using environment (don't forget to uncomment the QUICKSTART_ENVIRONMENT too)
#    env_file:
#      - env/.env.dev
  frontend:
    environment:
      - REACT_APP_API_HOST
    networks:
      - "quickstart"
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports: ["3000:3000"]
networks:
  quickstart:
    name: quickstart
